language: node_js
sudo: false
node_js: 
  - '12'
  - 'lts/*'
cache:
  directories:
  - node_modules
before_script:
  - yarn bootstrap
script:
  - travis_retry npm run test:ci
  - codecov
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  on:
    branch: master
  local-dir: docs/build
  target_branch: gh-pages
before_deploy:
- npm run docs:build
env:
  - MOZ_HEADLESS=1
addons:
  chrome: stable
  firefox: latest
branches:
  only:
    - master